"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowUpRight, Camera, Map, Search } from "lucide-react";
import { Page, PageHeader } from "@/components/ui/page";
import { Button } from "@/components/ui/button";
interface Mapping { interpretation: string; href: string; area: string; status: string; how: string }
interface Note { id: string; source_id: string; text: string; uncertain: boolean; topics: string[]; mapping?: Mapping }
interface Topic { id: string; label: string; href: string }
interface Data { sources: { id: string; name: string; href: string }[]; items: Note[]; topics: Topic[] }
const labels: Record<string,string> = { built: "Implemented in this overhaul", existing: "Uses an existing capability", concept: "Mapped product concept", unclear: "Uncertain reading", reference: "Preserved reference", "not-adopted": "Preserved, not treated as a decision" };
export default function OverhaulReviewPage() {
  const [data,setData] = useState<Data|null>(null); const [error,setError] = useState(""); const [query,setQuery] = useState(""); const [topic,setTopic] = useState("all"); const [source,setSource] = useState("all"); const [status,setStatus] = useState("all");
  async function load() { try { const r=await fetch("/api/overhaul"); const d=await r.json(); if(!r.ok) throw new Error(d.error); setData(d); setError(""); } catch(e) { setError(e instanceof Error?e.message:"Could not load notebook"); } }
  useEffect(()=>{ const params=new URLSearchParams(window.location.search); setTopic(params.get("topic")||"all"); setQuery(params.get("note")||""); void load(); },[]);
  const visible=data?.items.filter((n)=>(topic==="all"||n.topics.includes(topic))&&(source==="all"||n.source_id===source)&&(status==="all"||n.mapping?.status===status)&&`${n.id} ${n.text} ${n.mapping?.interpretation} ${n.mapping?.how}`.toLowerCase().includes(query.toLowerCase()))||[];
  return <Page className="max-w-6xl"><PageHeader title="Overhaul review" icon={Map}/>
    {error?<div role="alert" className="rounded-xl border border-warning/30 p-5 text-sm">{error}<Button className="ml-3" variant="outline" onClick={()=>void load()}>Retry</Button></div>:!data?<p role="status" className="p-8 text-sm text-muted-foreground">Loading your notebook…</p>:<>
      <section className="rounded-2xl border border-border bg-background p-4 sm:p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-sm font-medium">The areas your notes connect</h2><Button variant="ghost" size="sm" onClick={()=>{setTopic("all");setSource("all");setStatus("all");setQuery("");}}>Show all {data.items.length} entries</Button></div><div className="grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-4">{data.topics.map((t,i)=><button key={t.id} aria-pressed={topic===t.id} onClick={()=>{setTopic(topic===t.id?"all":t.id);setSource("all");}} className={`flex min-h-20 items-center gap-3 rounded-xl border p-3 text-left transition-transform duration-[var(--dur-fast)] ease-[var(--ease-out-custom)] active:scale-[0.97] ${topic===t.id?"border-primary/40 bg-secondary":"border-border bg-card"}`}><span aria-hidden="true" className="size-3 shrink-0 rounded-full" style={{background:`var(--chart-${i%5+1})`}}/><span className="text-xs font-medium">{t.label}</span></button>)}</div></section>
      <details className="rounded-xl border border-border p-4"><summary className="flex cursor-pointer items-center gap-2 text-sm"><Camera size={16}/>Original photographs</summary><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{data.sources.map(s=><div key={s.id}><a href={s.href} target="_blank" rel="noreferrer"><img src={s.href} alt={`Notebook page ${s.id}`} className="h-32 w-full rounded-lg border border-border object-cover" loading="lazy"/></a><button onClick={()=>{setSource(s.id);setTopic("all");setQuery("");}} className="mt-2 min-h-9 w-full rounded-lg border border-border text-xs active:scale-[0.97]">Notes from {s.id}</button></div>)}</div></details>
      <div className="flex flex-wrap gap-3"><label className="flex min-h-11 min-w-0 flex-1 items-center gap-2 rounded-lg border border-border bg-card px-3"><Search size={15}/><input aria-label="Search notes and interpretations" className="min-w-0 flex-1 bg-transparent text-sm outline-none" placeholder="Search a note, idea, or ID" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter incorporation status" className="min-h-11 max-w-full rounded-lg border border-border bg-card px-3 text-sm" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All incorporation states</option>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></div>
      <p className="text-xs text-muted-foreground">{visible.length} entries shown{source!=="all"?` from ${source}`:""}. Notes can belong to several areas. Questions and uncertain readings remain visible.</p>
      <div className="space-y-4">{visible.map(note=><article key={note.id} id={note.id} className="scroll-mt-20 overflow-hidden rounded-2xl border border-border bg-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3"><a href={`/api/overhaul?image=${note.source_id}`} target="_blank" rel="noreferrer" className="inline-flex min-h-8 items-center gap-1 font-mono text-xs text-muted-foreground">{note.id}<ArrowUpRight size={12}/></a><span className={`text-xs ${note.mapping?.status==="built"?"text-success":note.uncertain?"text-warning":"text-muted-foreground"}`}>{labels[note.mapping?.status||"reference"]}</span></div><div className="grid gap-5 p-4 sm:p-5 lg:grid-cols-[minmax(0,1fr)_minmax(0,1.3fr)]"><section><h2 className="mb-2 text-xs font-medium text-muted-foreground">Your note</h2><p className="whitespace-pre-wrap text-sm leading-relaxed">{note.text}</p>{note.uncertain&&<p className="mt-3 text-xs text-warning">Some handwriting is uncertain. The original reading has been preserved.</p>}</section><section><h3 className="text-xs font-medium text-muted-foreground">How I interpreted it</h3><p className="mt-2 text-sm leading-relaxed">{note.mapping?.interpretation||"Preserved for review."}</p><h3 className="mt-4 text-xs font-medium text-muted-foreground">Where and how</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{note.mapping?.how}</p>{note.mapping&&<Link href={note.mapping.href} className="mt-3 inline-flex min-h-9 items-center gap-2 rounded-lg border border-border px-3 text-xs active:scale-[0.97]">{note.mapping.area}<ArrowUpRight size={13}/></Link>}</section></div></article>)}</div>
      {visible.length===0&&<p className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No entries match. Clear the search or choose another area.</p>}
    </>}
  </Page>;
}
