import type { Material, Block, Skill } from "./model";
const exercise = (id: string, title: string, block: Block, skill: Skill, prompt: string, hint: string, example: string, variation: string, passage = ""): Material => ({ id, title, block, skill, language: "en", prompt, hint, example, variation, passage });
export const MATERIALS: Material[] = [
  exercise("change-of-mind", "A change of mind", "conversation", "structure", "Tell me about a decision you changed your mind about. What changed, and why?", "Set the scene, name the turning point, finish with the outcome.", "I planned to work alone on a feature. A colleague spotted a problem I had missed, so we paired on the next version. I still do the first sketch alone, but now ask for feedback earlier.", "Tell a different story about something that did not go as planned."),
  exercise("recommend", "Make a recommendation", "conversation", "point", "Recommend a place, book, or activity to a friend. Say who would enjoy it and why.", "Start with your recommendation. Add one reason and one example.", "I'd recommend the riverside walk if you want a quiet afternoon. It has enough shade to stay comfortable, and there is a small café halfway along.", "A friend has only an hour free. Recommend something different and explain your choice."),
  exercise("follow-up", "Stay with the question", "conversation", "response", "What makes a good weekend for you? Give your answer, then consider how it changes when you are travelling.", "Answer the question first. Add only the context the listener needs.", "A good weekend gives me time outside and one unhurried conversation. When I travel, I keep the same idea but leave the location open.", "What makes a workday satisfying, and does your answer change when you work with others?"),
  exercise("concrete-story", "Show what you mean", "conversation", "support", "Describe a quality you appreciate in a friend. Show it through one real example.", "Name the quality, describe a moment, explain what it showed.", "I appreciate reliability. A friend once checked in after an interview I had barely mentioned. That small detail made me feel remembered.", "Describe something you value in a team, using a different example."),
  exercise("tool", "The first sentence", "explanation", "point", "Explain a tool you use at work to someone who has never seen it. Begin with what it helps someone do.", "What it does, who it helps, one concrete example.", "A component library helps a team reuse the same interface pieces. For example, everyone can use one tested date picker instead of building a different one for every page.", "Explain a different tool to a colleague who already knows the field."),
  exercise("analogy", "Make an idea tangible", "explanation", "support", "Explain a technical idea using an example from everyday life. Say where the comparison stops being useful.", "Introduce the idea, give the analogy, name one limit.", "A cache is like keeping frequently used ingredients on the counter. You save trips to the cupboard. Unlike the ingredients, cached information can become outdated without looking different.", "Explain another idea through a concrete example, without reusing the same analogy."),
  exercise("process", "Walk someone through it", "explanation", "structure", "Explain a process you know well. Help the listener understand how each step leads to the next.", "Describe the goal before the steps. Connect steps using their purpose.", "To investigate a bug, I first reproduce it so I can tell whether a change helps. Then I isolate the failing part. Finally, I check both the fix and the original behavior.", "Explain a different process to someone who is doing it for the first time."),
  exercise("why", "Answer the actual question", "explanation", "response", "Someone asks why your team uses a particular tool. Answer why, without turning the answer into a full tutorial.", "Give the reason, support it, stop when you have answered.", "We use it because it makes changes easier to review. The shared history lets us see what changed and reverse a mistake when needed.", "Why would you choose a simpler solution over a more flexible one? Give a specific situation."),
  exercise("proposal", "A proposal in a minute", "presentation", "point", "Propose one improvement to a workflow. State the change and its benefit before discussing implementation.", "Recommendation, reason, example, next step.", "I suggest testing our most important user flow before every release. It would catch common breakages early. We can start with sign-in and expand once that check is reliable.", "Propose a different improvement with a smaller budget."),
  exercise("objection", "Respond to an objection", "presentation", "response", "You proposed improving a workflow. A colleague says: 'We don't have time for this.' Respond directly and fairly.", "Recognize the concern. Answer it. Offer a concrete tradeoff.", "Time is the main constraint. I would limit the first version to one hour and one workflow. If it does not save effort in the next two releases, we can reconsider.", "Respond to a different objection: 'The current system already works.'"),
  exercise("evidence", "Support your proposal", "presentation", "support", "Make a case for changing how a team works. Use a specific example without inventing statistics.", "Distinguish what you observed from what you expect.", "In our last review we repeated the same explanation three times. A short shared note could reduce that repetition. I would try it for one review before assuming it will help.", "Make a case for keeping a current practice. Support it with a different example."),
  exercise("update", "An update people can follow", "presentation", "structure", "Give a short project update: where things stand, what changed, and what decision is needed.", "Choose one main message. Group details around it.", "The prototype is ready for a trial. Testing exposed one slow step, which we have simplified. We now need to decide whether to test with five users this week.", "Give an update about a project that has encountered an unexpected problem."),
  exercise("reading", "Read, retell, discuss", "explanation", "structure", "Read the passage aloud. Then hide it and explain the idea in your own words. Reading practice does not update your spontaneous-speaking profile.", "Remember the problem, the change, and the result rather than the exact wording.", "The team reduced repeated questions by making the answers easier to find. They tested the change before expanding it.", "Describe a different situation where making information visible would help.", "A small team noticed that the same questions came up in every meeting. They did not add another meeting. Instead, they kept a short shared note with current decisions and unanswered questions. After two weeks, they asked whether the note had made conversations easier. They kept the parts people used and removed the rest."),
];
