import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { generate } from "../scripts/gen-inventory.mjs";

const appRoot = path.resolve(import.meta.dirname, "..");
const tempDirs: string[] = [];

afterEach(() => {
  for (const dir of tempDirs.splice(0)) fs.rmSync(dir, { recursive: true, force: true });
});

describe("route inventory", () => {
  it("matches the committed JSON and markdown generated from the app tree", () => {
    const entries = generate(appRoot) as Array<{
      kind: "page" | "api";
      route: string;
      methods: string[];
      dynamic: boolean;
      params: string[];
      hasColocatedTest: boolean;
    }>;
    const json = `[` + (entries.length ? `\n${entries.map((entry) => `  ${JSON.stringify(entry)}`).join(",\n")}\n` : "") + `]\n`;
    const markdown = [
      "# Routes",
      "",
      "Generated by `node scripts/gen-inventory.mjs`.",
      "",
      "| Route | Kind | Methods | Params | Colocated test |",
      "|-------|------|---------|--------|----------------|",
      ...entries.map(({ kind, route, methods, dynamic, params, hasColocatedTest }) =>
        `| ${route} | ${kind} | ${methods.join(", ") || "—"} | ${dynamic ? params.join(", ") : "—"} | ${hasColocatedTest ? "yes" : "no"} |`),
      "",
    ].join("\n");
    expect(fs.readFileSync(path.join(appRoot, "docs/routes.json"), "utf8")).toBe(json);
    expect(fs.readFileSync(path.join(appRoot, "docs/routes.md"), "utf8")).toBe(markdown);
  });

  it("finds new page and API files, including APIs with no exported methods", () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "lifeos-inventory-"));
    tempDirs.push(dir);
    fs.mkdirSync(path.join(dir, "src/app/api/example"), { recursive: true });
    fs.mkdirSync(path.join(dir, "src/app/example"), { recursive: true });
    fs.writeFileSync(path.join(dir, "src/app/api/example/route.ts"), "");
    fs.writeFileSync(path.join(dir, "src/app/example/page.tsx"), "");
    const entries = generate(dir);
    expect(entries).toContainEqual(expect.objectContaining({ kind: "page", route: "/example" }));
    expect(entries).toContainEqual(expect.objectContaining({ kind: "api", route: "/example", methods: [] }));
  });
});
