"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, BookOpen, FlaskConical, Link2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { WORKFLOW_META, STATE_LABEL, type WorkflowRun } from "@/lib/workflows/model";
export function WorkflowConnections() {
  const [runs,setRuns]=useState<WorkflowRun[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(false);
  const [query,setQuery]=useState(""); const [all,setAll]=useState(false);
  function load(){setLoading(true);fetch("/api/workflows").then(r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>{setRuns(d.runs);setError(false);}).catch(()=>setError(true)).finally(()=>setLoading(false));}
  useEffect(()=>{queueMicrotask(load);},[]);
  const filtered=runs.filter(r=>`${r.title} ${r.report?.kind||r.kind}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-medium">Where your ideas go</h2><p className="mt-1 text-sm text-muted-foreground">Follow each source through its workflow to a saved outcome.</p></div><Link href="/review" className="inline-flex min-h-9 items-center gap-1 text-xs underline">Notebook map<ArrowUpRight size={12}/></Link></div>
    <input value={query} onChange={e=>{setQuery(e.target.value);setAll(false);}} aria-label="Find a workflow connection" placeholder="Find an idea or workflow" className="min-h-11 w-full rounded-lg border border-border bg-card px-3 text-sm"/>
    {error?<p className="rounded-xl border border-warning/30 p-4 text-sm">Could not load connections. <button className="underline" onClick={load}>Retry</button></p>:loading?<p role="status" className="p-6 text-sm text-muted-foreground">Loading source paths…</p>:filtered.length===0?<div className="rounded-2xl border border-dashed border-border p-8 text-center"><Link2 size={28} className="mx-auto mb-4 text-muted-foreground"/><p className="text-sm">{runs.length?"No matching paths.":"Source paths appear when you develop a saved idea."}</p><Button asChild variant="outline" className="mt-4"><Link href="/workflows">Open workflows</Link></Button></div>:<div className="space-y-4">{(all?filtered:filtered.slice(0,12)).map(run=>{const meta=WORKFLOW_META[run.report?.kind||run.kind];return <div key={run.id} className="grid items-center gap-2 rounded-2xl border border-border bg-background p-4 md:grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)_auto_minmax(0,1fr)]"><div className="rounded-xl border border-border bg-card p-4"><p className="mb-2 flex items-center gap-2 text-xs text-muted-foreground"><BookOpen size={14}/>Source</p><p className="text-sm font-medium [overflow-wrap:anywhere]">{run.title}</p></div><div className="flex items-center justify-center gap-1 text-[10px] text-muted-foreground"><span>developed as</span><ArrowRight size={13}/></div><Link href={`/workflows?run=${run.id}`} className="rounded-xl border border-primary/30 bg-card p-4 active:scale-[0.97]"><p className="mb-2 flex items-center gap-2 text-xs text-muted-foreground"><FlaskConical size={14}/>Workflow</p><p className="text-sm font-medium">{meta.label}</p><p className="mt-2 text-xs text-muted-foreground">{STATE_LABEL[run.state]}</p></Link><div className="flex items-center justify-center gap-1 text-[10px] text-muted-foreground"><span>{run.destination?"saved to":"proposed for"}</span><ArrowRight size={13}/></div><Link href={run.destination||meta.href} className={`rounded-xl border bg-card p-4 text-sm active:scale-[0.97] ${run.destination?"border-border":"border-dashed border-border"}`}><p className="text-xs text-muted-foreground">{run.destination?"Destination":"Possible destination"}</p><p className="mt-2 font-medium capitalize">{(run.destination||meta.href).replace(/^\//,"").replace(/-/g," ")}</p></Link></div>;})}{!all&&filtered.length>12&&<Button variant="outline" onClick={()=>setAll(true)}>Show all paths</Button>}</div>}
  </section>;
}
